### PR TITLE
Fix missing config/ folder

### PR DESCRIPTION
**Pull request by nm17**

### CODE REVIEW

**Comment by nm17** [comment]
I have zero idea how to add it without errors. Every time I try it just says this:
```
> Task :launcher:compileKotlin FAILED
14 actionable tasks: 1 executed, 13 up-to-date
e: Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
    class com.deflatedpickle.quiver.config.QuiverSettings, unresolved supertypes: kotlin.script.templates.standard.ScriptTemplateWithArgs

e: [...]\Quiver\launcher\src\main\kotlin\com\deflatedpickle\quiver\launcher\main.kt: (189, 98): Cannot access 'kotlin.script.templates.standard.ScriptTemplateWithArgs' which is a supertype of 'com.deflatedpickle.quiver.config.QuiverSettings'. Check your module classpath for missing or conflicting dependencies
e: [...]\Quiver\launcher\src\main\kotlin\com\deflatedpickle\quiver\launcher\main.kt: (189, 98): Unresolved reference: language

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':launcher:compileKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
```

**Comment by DeflatedPickle** [comment]
That is the runtime config folder, not the script config package. This error is because you haven't included my suggestion in #17 and in doing so, causing Kotlin magic to fail

**Comment by nm17** [comment]
@DeflatedPickle 
idea64_OATS5SG9Rj

**Comment by nm17** [comment]
@DeflatedPickle With config/ commented out
idea64_N00HQ9J0Uc

**Comment by nm17** [comment]
Wait nvm

**Comment by nm17** [comment]
I absolutely don't get it then. Too bad I barely know Kotlin.

**Comment by DeflatedPickle** [comment]
It's missing a class. Please read my suggestion in #17, where I give you the class that didn't get committed

**Comment by nm17** [comment]
> 
> 
> It's missing a class. Please read my suggestion in #17, where I give you the class that didn't get committed

I didn't commit it yet because it doesn't build. I copied you code snippet and pasted it in `core/src/main/kotlin/com/deflatedpickle/quiver/config/QuiverSettings.kts` and it doesn't build. Error is above.

**Comment by nm17** [comment]
Nvm it's because it's named .kts and not .kt. I'll add it now pls check

**Comment by DeflatedPickle** [comment]
The pull request is to remove a folder from the ignore file, that I **want** ignored, as it contains user configs generated at runtime - I don't want to commit the files from my testing, so no, sorry

**Comment by nm17** [comment]
Oh, I'll remove it.

**Pull request closed without merging**
